### ISSUE TITLE
[Bug] TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-event-app-data-processor#24]
``` bash
(mozfest-2016-event-app-data-processor) mavisou:~/Development/mozfest-event-app-data-processor[master*]$ python update_schedule.py 
Fetched the data ...
Traceback (most recent call last):
  File "update_schedule.py", line 489, in <module>
    update_schedule()
  File "update_schedule.py", line 444, in update_schedule
    commit_json(session_json)
  File "update_schedule.py", line 426, in commit_json
    branch=branch
  File "/Users/mavisou/.virtualenvs/mozfest-2016-event-app-data-processor/lib/python2.7/site-packages/github3/decorators.py", line 38, in auth_wrapper
    return func(self, *args, **kwargs)
  File "/Users/mavisou/.virtualenvs/mozfest-2016-event-app-data-processor/lib/python2.7/site-packages/github3/repos/repo.py", line 1828, in update_file
    if 'content' in json and 'commit' in json:
TypeError: argument of type 'NoneType' is not iterable

```

**Comment by mmmavis** [comment]
Aha! This was because https://github.com/mozfest-bot wasn't a collaborator on http://github.com/mozilla/mozfest-event-app/ 😉
